spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ironsale?useUnicode=true&characterEncoding=UTF-8
    #url: jdbc:mysql:///demo_inxedu_v2_0_open?zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
  thymeleaf: #springboot建议将缓存关闭
    cache: false


  mvc:
    static-path-pattern: /static/**
  redis:
    #    host: 172.16.23.199
    #    host: 172.16.23.177
    host: 47.93.244.114
    port: 6379
    jedis:
      pool:
        max-wait: 330000  #链接池最大阻塞等待时间
        max-active: 100   # 连接池最大连接数(使用负值标识没有限制)
        max-idle: 20      # 连接池中最大空闲链接
        min-idle: 0       # 连接池中最小空闲链接
    timeout: 3000         # 链接超时

server:
  port: 80



mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: com.ycxy.steelsales.pojo
    # spring boot集成mybatis的方式打印sql
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  config:
    com: debug
debug: true